In [9]:
# Packages Importing
!pip install yfinance
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt

##########################################


start_date = dt.datetime(2022,1,1)
end_date = dt.datetime(2022,9,1)

tickers = ['AGG', 'AUBAX', 'CWI', 'VTI']

yf.pdr_override()

df = yf.download(tickers, start_date, end_date)
df.head(10)

[*********************100%***********************]  4 of 4 completed

             Adj Close                                         Close         \
                   AGG      AUBAX        CWI         VTI         AGG  AUBAX
Date
2022-01-03  110.743881  10.376155  28.579782  240.230408  113.300003  10.49
2022-01-04  110.734100  10.346481  28.667093  239.775604  113.290001  10.46
2022-01-05  110.391998  10.336589  28.366356  234.574905  112.940002  10.45
2022-01-06  110.274704  10.306917  28.298449  234.515579  112.820000  10.42
2022-01-07  109.952148  10.316807  28.463369  233.447769  112.489998  10.43
2022-01-10  109.854401  10.306917  28.269344  233.042374  112.389999  10.42
2022-01-11  110.059662  10.326697  28.657394  235.365891  112.599998  10.44

                                         High         ...        Low  \
                  CWI         VTI         AGG  AUBAX  ...        CWI
Date                                                  ...
2022-01-03  29.459999  242.970001  113.680000  10.49  ...  29.309999
2022-01-04  29.549999  242.509995  113.300003  10.46  ...  29.469999
2022-01-05  29.240000  237.250000  113.360001  10.45  ...  29.240000
2022-01-06  29.170000  237.190002  112.839996  10.42  ...  29.080000
2022-01-07  29.340000  236.110001  112.709999  10.43  ...  29.120001
2022-01-10  29.139999  235.699997  112.419998  10.42  ...  28.910000
2022-01-11  29.540001  238.050003  112.629997  10.44  ...  29.200001

                              Open                                   Volume  \
                   VTI         AGG  AUBAX        CWI         VTI        AGG
Date
2022-01-03  240.860001  113.669998  10.49  29.410000  242.419998  9399200.0
2022-01-04  241.350006  113.220001  10.46  29.580000  243.729996  7772100.0
2022-01-05  237.199997  113.339996  10.45  29.600000  242.080002  8530900.0
2022-01-06  235.539993  112.750000  10.42  29.209999  237.199997  8866500.0
2022-01-07  235.320007  112.690002  10.43  29.209999  237.190002  9018900.0
2022-01-10  230.970001  112.230003  10.42  29.110001  234.210007  8074900.0
2022-01-11  234.089996  112.330002  10.44  29.219999  235.710007  6728600.0


           AUBAX      CWI      VTI
Date
2022-01-03     0   555800  4204000
2022-01-04     0   358600  4217000
2022-01-05     0  1139800  4878300
2022-01-06     0   371500  4519200
2022-01-07     0   412400  3580200
2022-01-10     0  1558200  5819600
2022-01-11     0   684500  3524800

[7 rows x 24 columns]